import type { Metadata, Viewport } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { PageTransitionProvider } from "./components/PageTransitionProvider";
import PreloaderGate from "./components/PreloaderGate";
import { LayoutProvider } from "./context/LayoutContext";

const roobertSans = localFont({
	src: [
		{
			path: "../public/fonts/RoobertTRIAL-Light.woff2",
			weight: "300",
			style: "normal",
		},
		{
			path: "../public/fonts/RoobertTRIAL-LightItalic.woff2",
			weight: "300",
			style: "italic",
		},
		{
			path: "../public/fonts/RoobertTRIAL-Regular.woff2",
			weight: "400",
			style: "normal",
		},
		{
			path: "../public/fonts/RoobertTRIAL-RegularItalic.woff2",
			weight: "400",
			style: "italic",
		},
		{
			path: "../public/fonts/RoobertTRIAL-Medium.woff2",
			weight: "500",
			style: "normal",
		},
		{
			path: "../public/fonts/RoobertTRIAL-MediumItalic.woff2",
			weight: "500",
			style: "italic",
		},
		{
			path: "../public/fonts/RoobertTRIAL-SemiBold.woff2",
			weight: "600",
			style: "normal",
		},
		{
			path: "../public/fonts/RoobertTRIAL-SemiBoldItalic.woff2",
			weight: "600",
			style: "italic",
		},
		{
			path: "../public/fonts/RoobertTRIAL-Bold.woff2",
			weight: "700",
			style: "normal",
		},
		{
			path: "../public/fonts/RoobertTRIAL-BoldItalic.woff2",
			weight: "700",
			style: "italic",
		},
		{
			path: "../public/fonts/RoobertTRIAL-Heavy.woff2",
			weight: "800",
			style: "normal",
		},
		{
			path: "../public/fonts/RoobertTRIAL-HeavyItalic.woff2",
			weight: "800",
			style: "italic",
		},
	],
	variable: "--font-roobert-sans",
});

const roobertMono = localFont({
	src: [
		{
			path: "../public/fonts/RoobertMonoTRIAL-Light.woff2",
			weight: "100",
			style: "normal",
		},
		{
			path: "../public/fonts/RoobertMonoTRIAL-LightItalic.woff2",
			weight: "300",
			style: "italic",
		},
		{
			path: "../public/fonts/RoobertMonoTRIAL-Regular.woff2",
			weight: "400",
			style: "normal",
		},
		{
			path: "../public/fonts/RoobertMonoTRIAL-RegularItalic.woff2",
			weight: "400",
			style: "italic",
		},
		{
			path: "../public/fonts/RoobertMonoTRIAL-Medium.woff2",
			weight: "500",
			style: "normal",
		},
		{
			path: "../public/fonts/RoobertMonoTRIAL-MediumItalic.woff2",
			weight: "500",
			style: "italic",
		},
		{
			path: "../public/fonts/RoobertMonoTRIAL-SemiBold.woff2",
			weight: "600",
			style: "normal",
		},
		{
			path: "../public/fonts/RoobertMonoTRIAL-SemiBoldItalic.woff2",
			weight: "600",
			style: "italic",
		},
		{
			path: "../public/fonts/RoobertMonoTRIAL-Bold.woff2",
			weight: "700",
			style: "normal",
		},
		{
			path: "../public/fonts/RoobertMonoTRIAL-BoldItalic.woff2",
			weight: "700",
			style: "italic",
		},
		{
			path: "../public/fonts/RoobertMonoTRIAL-Heavy.woff2",
			weight: "800",
			style: "normal",
		},
		{
			path: "../public/fonts/RoobertMonoTRIAL-HeavyItalic.woff2",
			weight: "800",
			style: "italic",
		},
	],
	variable: "--font-roobert-mono",
});

const roobertSemiMono = localFont({
	src: [
		{
			path: "../public/fonts/RoobertSemiMonoTRIAL-Light.woff2",
			weight: "100",
			style: "normal",
		},
		{
			path: "../public/fonts/RoobertSemiMonoTRIAL-LightItalic.woff2",
			weight: "300",
			style: "italic",
		},
		{
			path: "../public/fonts/RoobertSemiMonoTRIAL-Regular.woff2",
			weight: "400",
			style: "normal",
		},
		{
			path: "../public/fonts/RoobertSemiMonoTRIAL-RegularItalic.woff2",
			weight: "400",
			style: "italic",
		},
		{
			path: "../public/fonts/RoobertSemiMonoTRIAL-Medium.woff2",
			weight: "500",
			style: "normal",
		},
		{
			path: "../public/fonts/RoobertSemiMonoTRIAL-MediumItalic.woff2",
			weight: "500",
			style: "italic",
		},
		{
			path: "../public/fonts/RoobertSemiMonoTRIAL-SemiBold.woff2",
			weight: "600",
			style: "normal",
		},
		{
			path: "../public/fonts/RoobertSemiMonoTRIAL-SemiBoldItalic.woff2",
			weight: "600",
			style: "italic",
		},
		{
			path: "../public/fonts/RoobertSemiMonoTRIAL-Bold.woff2",
			weight: "700",
			style: "normal",
		},
		{
			path: "../public/fonts/RoobertSemiMonoTRIAL-BoldItalic.woff2",
			weight: "700",
			style: "italic",
		},
		{
			path: "../public/fonts/RoobertSemiMonoTRIAL-Heavy.woff2",
			weight: "800",
			style: "normal",
		},
		{
			path: "../public/fonts/RoobertSemiMonoTRIAL-HeavyItalic.woff2",
			weight: "800",
			style: "italic",
		},
	],
	variable: "--font-roobert-semi-mono",
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
	formatDetection: {
		telephone: false,
	},
};

export const viewport: Viewport = {
	themeColor: "#050508",
	viewportFit: "cover",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={`${roobertSans.variable} ${roobertMono.variable} ${roobertSemiMono.variable} antialiased`}>
				<PageTransitionProvider>
					<LayoutProvider>
						<PreloaderGate />
						{children}
					</LayoutProvider>
				</PageTransitionProvider>
			</body>
		</html>
	);
}
